spring.application.name=student-service

# MongoDB connection URL
spring.data.mongodb.uri=mongodb://root:mongo@localhost:27017/eca_students?authSource=admin&autoIndexCreation=true

# Server Configuration
server.port=8082
server.servlet.context-path=/student-service

# Eureka Client Configuration
eureka.client.serviceUrl.defaultZone=http://10.128.0.13:8761/eureka/