spring.application.name=media-service

# Storage Configuration - Using Google Cloud Storage
storage.type=gcs
gcs.bucket-name=${GCS_BUCKET_NAME:media-files}
gcs.project-id=${GCS_PROJECT_ID:}
gcs.credentials-path=${GCS_CREDENTIALS_PATH:}

# Server Configuration
server.port=8083
server.servlet.context-path=/media-service

# Eureka Client Configuration
eureka.client.serviceUrl.defaultZone=http://10.128.0.13:8761/eureka/

